---
- name: playbook for simple 10 GB partition
  hosts: DBVMS 
  become: true
  tasks:
  - name: collect facts about system services
    service_facts:
     name: abrtd
     source: systemd
    register: services_state

  - name: Debug
    debug:
     var: services_state
